### PR TITLE
MMSP-11404 (Mark) Add helper to check if a Windows service is running

### PR DESCRIPTION
**Pull request by dgolub**
@markbenvenuto

### CODE REVIEW

**Comment by markbenvenuto** [comment]
It feels like this could be simply composed out some of the existing functions in this file. The only difference is the access level you use to open the service with in this incarnation.

**Comment by dgolub** [comment]
Right, I deliberately didn't use the existing classes so that a non-administrator can use this function to check the status of a service.  It probably doesn't matter much for our use case, since the Automation Agent should always have administrator access, but I figured it wouldn't hurt.

**Comment by markbenvenuto** [comment]
I would add a comment for future users that this method requires a lower level of privileges.

:+1:

**Comment by dgolub** [comment]
Merged c258ce1.

**Pull request closed without merging**
